query getAlbum($id:ID!) {
  getAlbum(id:$id) {
    _id
    name
    imgUrl
    artists {
      _id
      name
      imgUrl
      coverImgUrl	
      Followers
    }
    tracks {
      _id
      trackName
      audioUrl
      view
      like
    }
  }
}