query getTrack($id:ID!) {
  getTrack(id:$id) {
    _id
    imgUrl
    audioUrl
    trackName
    view
    artists {
      _id
      name
      imgUrl
      coverImgUrl
      Followers
    }
    createdAt
    updatedAt
  }
}