query getTracks($actorID:ID , $pagination:Pagination , $sort:getTracksSort) {
  getTracks(input:{
    actorID:$actorID
  },
  pagination:$pagination , sort:$sort) {
     _id
    imgUrl
    audioUrl
    trackName
    actors {
      _id
      name
      imgUrl
      coverImgUrl
      Followers
    }
    view
    like
    createdAt
    updatedAt
  }
}